"use client";
import { ArrowRight, Plus, Trophy, Target, CheckCircle2, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { TaskList } from './workspace-ui';
import { teams, type Task, type Proposal } from '@/lib/domain';
import type { Account } from '@/lib/auth-types';
export type Standing = typeof teams[number] & { points: number };
export function Dashboard({ account, tasks, proposals, standings, onNavigate, onCreate, onOpen, busy }: { account: Account; tasks: Task[]; proposals: Proposal[]; standings: Standing[]; onNavigate: (tab: string) => void; onCreate: () => void; onOpen: (id: string) => void; busy: boolean }) {
  const business = account.role === 'business';
  const published = tasks.filter(t => t.published);
  const team = teams.find(t => t.id === account.teamId);
  const points = standings.find(t => t.id === account.teamId)?.points || 0;
  const recommended = published.filter(t => t.score >= 40).sort((a,b) => {
    const match = (t: Task) => team?.interests.toLowerCase().includes(t.topic.toLowerCase()) ? 1 : 0;
    return match(b) - match(a) || b.score - a.score;
  }).slice(0,3);
  const reviewCount = proposals.filter(p => p.evidenceSubmittedAt && !p.milestone && p.status === 'chosen').length;
  return <>
    <div className="page-heading"><div><div className="section-label">{business ? 'КАБИНЕТ БИЗНЕСА' : 'КАБИНЕТ КОМАНДЫ'}</div><h1 id="page-title" tabIndex={-1}>{business ? 'От запроса к результату' : `Привет, ${account.name}!`}</h1><p>{business ? 'Создавайте понятные задачи и находите мотивированные команды.' : 'Выбирайте интересные задачи. Предлагайте решения. Показывайте результат.'}</p></div><span className="workspace-chip">AI Sana · Практический хакатон</span></div>
    <section className="dashboard-hero"><div><span className="eyebrow"><Sparkles size={15} />{business ? 'КАЧЕСТВО ЗАДАЧИ ОТКРЫВАЕТ ВОЗМОЖНОСТИ' : 'ВАШ СЛЕДУЮЩИЙ ВЫЗОВ УЖЕ ЗДЕСЬ'}</span><h2>{business ? 'Хорошая задача начинается\nс понятного описания.' : 'Превратите знания\nв работающий проект.'}</h2><p>{business ? 'Добавьте данные, критерии успеха и ограничения. Чем полнее карточка, тем выше она в каталоге.' : 'Все опубликованные задачи открыты для вашей команды. Бизнес выбирает исполнителей, а баллы приходят за подтверждённый прогресс.'}</p><Button disabled={busy} onClick={business ? onCreate : () => onNavigate('catalog')}>{business ? <Plus size={17} /> : <Target size={17} />}{business ? 'Создать задачу' : 'Найти задачу'}<ArrowRight size={17} /></Button></div><div className="hero-orbit"><div className="hero-score"><span>{business ? 'ЦЕЛЬ ГОТОВНОСТИ' : 'ВАШ ПРОГРЕСС'}</span><strong>{business ? '100' : points}</strong><small>{business ? 'баллов за ясность' : 'баллов за результат'}</small></div><span className="orbit-label"><CheckCircle2 size={14} />{business ? 'За подтверждённые сведения' : 'Проверено бизнесом'}</span></div></section>
    <div className="dashboard-metrics">{(business ? [{ label: 'Опубликовано задач', value: published.length, tab: 'mine' }, { label: 'Черновиков', value: tasks.filter(t => !t.published).length, tab: 'mine' }, { label: 'Новых откликов', value: proposals.filter(p => p.status === 'pending').length, tab: 'offers' }, { label: 'Результатов на проверке', value: reviewCount, tab: 'offers' }] : [{ label: 'Открытых задач', value: published.length, tab: 'catalog' }, { label: 'Моих предложений', value: proposals.length, tab: 'offers' }, { label: 'В работе', value: proposals.filter(p => p.status === 'chosen' && !p.milestone).length, tab: 'offers' }, { label: 'Подтверждено этапов', value: proposals.filter(p => p.milestone).length, tab: 'offers' }]).map(item => <button key={item.label} onClick={() => onNavigate(item.tab)}><span>{item.label}</span><strong>{item.value}</strong><ArrowRight size={16} /></button>)}</div>
    <div className="dashboard-columns"><section className="dashboard-block"><div className="block-title"><div><span className="section-label">{business ? 'СЛЕДУЮЩИЕ ШАГИ' : 'РЕКОМЕНДАЦИИ'}</span><h2>{business ? 'Держите работу в движении' : 'Под ваши интересы'}</h2></div><Button variant="ghost" onClick={() => onNavigate(business ? 'offers' : 'catalog')}>Все<ArrowRight size={14} /></Button></div>{business ? <div className="action-checklist"><button onClick={() => onNavigate('mine')}><span>01</span><div><b>Уточните карточки</b><p>{published.filter(t => t.score < 70).length} опубликованных задач можно усилить</p></div><ArrowRight size={16} /></button><button onClick={() => onNavigate('offers')}><span>02</span><div><b>Сравните предложения</b><p>Выберите одну, несколько или ни одной команды</p></div><ArrowRight size={16} /></button><button onClick={() => onNavigate('offers')}><span>03</span><div><b>Проверьте результат</b><p>{reviewCount ? `${reviewCount} отчётов ждут подтверждения` : 'Начисляйте баллы после проверки этапа'}</p></div><ArrowRight size={16} /></button></div> : <><p className="help recommendation-note">По интересам команды и готовности от 40 баллов. Выбор задачи остаётся за вами.</p><TaskList tasks={recommended} proposals={proposals} onOpen={onOpen} disabled={busy} /></>}</section><aside className="dashboard-block leaderboard"><div className="block-title"><div><span className="section-label">ЗА ФАКТИЧЕСКИЙ ПРОГРЕСС</span><h2>Достижения команд</h2></div><Trophy size={22} /></div>{standings.map((standing, i) => <div className={'leaderboard-row ' + (standing.id === account.teamId ? 'is-me' : '')} key={standing.id}><span>{i + 1}</span><span className="profile-badge">{standing.initials}</span><b>{standing.name}</b><strong>{standing.points}<small> баллов</small></strong></div>)}<p className="help">+20 за подтверждённый этап. Отправка отклика и выбор команды баллов не дают.</p></aside></div>
  </>;
}
