import assert from 'node:assert/strict';
const base = process.env.TEST_URL || 'http://localhost:4173';
const headers = { 'Content-Type': 'application/json', Origin: base };
async function request(path, cookie = '', body, expected = 200) {
  const response = await fetch(base + path, { method: body === undefined ? 'GET' : 'POST', headers: { ...headers, Cookie: cookie }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const data = await response.json();
  assert.equal(response.status, expected, JSON.stringify(data));
  return { data, response };
}
const post = async (cookie, action, payload = {}, expected = 200) => (await request('/api/workspace', cookie, { action, ...payload }, expected)).data;
const state = async cookie => (await request('/api/workspace', cookie)).data;
async function login(email, password) {
  const { response, data } = await request('/api/auth', '', { action: 'login', email, password });
  const cookie = response.headers.get('set-cookie');
  assert.ok(cookie.includes('HttpOnly') && cookie.includes('SameSite=Strict'));
  assert.equal(data.account.email, email);
  return cookie.split(';')[0];
}
await request('/api/workspace', '', undefined, 401);
await request('/api/auth', '', { action: 'login', email: 'admin@sana.demo', password: 'incorrect' }, 401);
const admin = await login('admin@sana.demo', 'AdminSana2026!');
const student = await login('student@sana.demo', 'StudentSana2026!');
const student2 = await login('team2@sana.demo', 'StudentSana2026!');
let initial = await state(admin);
assert.equal(initial.tasks.length, 5); assert.equal(initial.proposals.length, 5);
assert.deepEqual(initial.tasks.map(t => t.score).sort((a,b) => b-a), [100,85,70,45,20]);
assert.equal(initial.ai.enabled, false);
const studentState = await state(student);
assert.deepEqual(studentState.tasks.map(t => t.id).sort(), initial.tasks.map(t => t.id).sort());
assert.ok(studentState.proposals.every(p => p.teamId === 't1'));
await post(student, 'saveTask', { task: { title: 'Forbidden' } }, 403);
await post(student, 'questions', { task: { draft: 'Forbidden text' } }, 403);
await post(student, 'decide', { id: initial.proposals[0].id, status: 'chosen' }, 403);
await post(student, 'milestone', { id: initial.proposals[0].id, evidence: 'Fake result' }, 403);
await post(admin, 'propose', {}, 403);
console.log('PASS: login, shared catalog, private proposals and server role enforcement.');
const q = await post(admin, 'questions', { task: { draft: 'Хотим автоматизировать заявки клиентов.' } });
assert.ok(q.questions.length >= 3);
const { task: draft } = await post(admin, 'saveTask', { task: { title: 'Private draft', context: 'Private working context' } });
assert.equal(draft.score, 0);
assert.ok(!(await state(student)).tasks.some(t => t.id === draft.id));
let { task } = await post(admin, 'saveTask', { task: { title: 'Тестовый кейс: заявки', org: 'Учебная организация', context: 'Обращения теряются между менеджерами.', published: true, confirmed: true } });
assert.equal(task.score, 10);
assert.ok((await state(student)).tasks.some(t => t.id === task.id));
await post(admin, 'saveTask', { task: { ...task, confirmed: false } }, 400);
await post(admin, 'saveTask', { task: { ...task, published: false } }, 400);
await post(admin, 'saveTask', { task: { ...task, revision: 0 } }, 409);
const offer = { taskId: task.id, teamId: 't2', idea: 'Единая форма и очередь обращений.', plan: 'Соберём процесс, затем прототип и проверим.', term: '2 недели', link: 'https://example.com/test-prototype' };
await post(student, 'propose', { proposal: { ...offer, taskId: draft.id } }, 404);
await post(student, 'propose', { proposal: { ...offer, link: 'javascript:alert(1)' } }, 400);
await post(student, 'propose', { proposal: { ...offer, link: 'https://user:pass@example.com' } }, 400);
const id = crypto.randomUUID();
const results = await Promise.all([post(student, 'propose', { proposal: offer, requestId: id }), post(student, 'propose', { proposal: offer, requestId: id })]);
const proposal = results[0].proposal;
assert.equal(proposal.teamId, 't1', 'Client cannot impersonate another team');
assert.equal(results[1].proposal.id, proposal.id);
assert.equal((await state(admin)).proposals.filter(p => p.id === id).length, 1);
await post(student, 'propose', { proposal: { ...offer, idea: 'Changed idea under reused identifier' }, requestId: id }, 409);
await post(student2, 'propose', { proposal: offer, requestId: id }, 409);
const { proposal: second } = await post(student2, 'propose', { proposal: offer });
assert.ok(!(await state(student2)).proposals.some(p => p.id === proposal.id));
console.log('PASS: drafts, confirmation, score, low-score open access, URLs, unlimited submissions and idempotency.');
await post(student, 'submitProgress', { id: proposal.id, evidence: 'Нельзя до выбора команды' }, 400);
await post(admin, 'decide', { id: proposal.id, status: 'chosen' });
await post(admin, 'decide', { id: second.id, status: 'chosen' });
await post(admin, 'milestone', { id: proposal.id, evidence: 'Преждевременное подтверждение' }, 400);
await post(student2, 'submitProgress', { id: proposal.id, evidence: 'Чужой результат для подмены' }, 403);
await post(student, 'submitProgress', { id: proposal.id, evidence: 'Проверили 20 обращений, 19 классифицированы верно. https://example.com/result' });
assert.equal((await state(student)).leaderboard.find(t => t.id === 't1').points, 0);
await post(admin, 'milestone', { id: proposal.id, evidence: 'Проверено 20 обращений, результат принят: 95% корректных категорий.' });
await post(admin, 'milestone', { id: proposal.id, evidence: 'Повторная отправка подтверждения' });
await post(admin, 'decide', { id: proposal.id, status: 'rejected' }, 400);
await post(student, 'submitProgress', { id: proposal.id, evidence: 'Изменить принятый результат' }, 400);
assert.equal((await state(student)).leaderboard.find(t => t.id === 't1').points, 20);
await post(admin, 'decide', { id: second.id, status: 'rejected' });
({ task } = await post(admin, 'saveTask', { task: { ...task, data: 'Синтетические обращения в CSV.', success: 'Из 20 заявок минимум 18 распознаны верно.' } }));
assert.equal(task.score, 45);
const competing = await Promise.all(['A', 'B'].map(async suffix => (await fetch(base + '/api/workspace', { method: 'POST', headers: { ...headers, Cookie: admin }, body: JSON.stringify({ action: 'saveTask', task: { ...task, title: 'Concurrent revision ' + suffix } }) })).status));
assert.deepEqual(competing.sort(), [200,409]);
console.log('PASS: manual multiple selection/rejection, student evidence, confirmed progress, exactly-once points and concurrent edits.');
const crossOrigin = await fetch(base + '/api/workspace', { method: 'POST', headers: { ...headers, Cookie: admin, Origin: 'https://untrusted.example' }, body: '{}' });
assert.equal(crossOrigin.status, 403);
for (const invalid of ['null','[]','{']) {
  const res = await fetch(base + '/api/workspace', { method: 'POST', headers: { ...headers, Cookie: admin, Connection: 'close' }, body: invalid });
  assert.equal(res.status,400); await res.text();
}
await request('/api/workspace', 'sana_auth=' + 'a'.repeat(64), undefined, 401);
await request('/api/auth', student, { action: 'logout' });
await request('/api/workspace', student, undefined, 401);
assert.equal((await request('/api/auth', student)).data.account, null);
console.log('PASS: origin validation, invalid payloads, forged sessions and logout revocation.');
